config/routes.rb
Rails.application.routes.draw do

  get 'my/curriculums'

  get 'my/worksheets'

  get 'my/courses'

  devise_for :users

  resources :questions do
    resources :question_comments
  end
  
  resources :dashboard
  
  resources :curriculums

  resources :courses do
    resources :course_comments
  end

  resources :hw_records

  resources :worksheets do
    resources :worksheet_comments
  end

  get 'home/contact'
  
  get 'home/AboutUs'
  

  
  get 'my/questions'

  get 'question_comments/destory'
  
  get 'question_comments/create'

  get 'question_comments/destroy'
  
  devise_scope :user do
    root to: "devise/sessions#new" 
  end
   
  mathjax 'mathjax'

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :course_comments
  has_and_belongs_to_many :worksheets
  has_and_belongs_to_many :curriculums
end

app/models/course_comment.rb
class CourseComment < ActiveRecord::Base
end

app/models/courseandcurriculum.rb
class Courseandcurriculum < ActiveRecord::Base
end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
  has_many :general_comments
  has_and_belongs_to_many :curriculums
end

app/models/general_comment.rb
class GeneralComment < ActiveRecord::Base
end

app/models/hw_record.rb
class HwRecord < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :question_comments
  has_and_belongs_to_many :worksheets
end

app/models/question_comment.rb
class QuestionComment < ActiveRecord::Base
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/worksheet.rb
class Worksheet < ActiveRecord::Base
  has_many :worksheet_comments
  has_and_belongs_to_many :questions
  has_and_belongs_to_many :courses
end

app/models/worksheet_comment.rb
class WorksheetComment < ActiveRecord::Base
end

app/models/worksheetandcourse.rb
class Worksheetandcourse < ActiveRecord::Base
end

app/controllers/my_controller.rb
class MyController < ApplicationController
  def questions
   @questions = Question.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end

  def worksheets
    @worksheets = Worksheets.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end
  
  def courses
    @courses = Courses.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end
  
  def curriculums
    @curriculums = Curriculums.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end
end

app/controllers/worksheets_controller.rb
class WorksheetsController < ApplicationController
  before_action :set_worksheet, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @worksheets = Worksheet.all
    respond_with(@worksheets)
  end

  def show
    respond_with(@worksheet)
  end

  def new
    @worksheet = Worksheet.new
    respond_with(@worksheet)
  end

  def edit
  end

  def create
    @worksheet = Worksheet.new(worksheet_params)
    @worksheet.save
    respond_with(@worksheet)
  end

  def update
    @worksheet.update(worksheet_params)
    respond_with(@worksheet)
  end

  def destroy
    @worksheet.destroy
    respond_with(@worksheet)
  end

  private
    def set_worksheet
      @worksheet = Worksheet.find(params[:id])
    end

    def worksheet_params
      params.require(:worksheet).permit(:author, :description, :worksheet_name, :suggested_grade, :arithmetic, :addition, :subtraction, :multiplication, :division, :long_division, :reading, :trick_question, :multiple_choices, :multiple_choice_answer, :word_problem, :word_problem_solution_equation, :integer, :decimal, :number_of_decimals, :fraction, :fraction_to_decimal, :decimal_to_fraction, :significant_digits, :scientific_notation, :parenthesis, :exponent, :roots, :square_root, :cube_root, :factoring, :foil, :variables, :number_of_variables, :imaginary_number, :degree, :radian, :trigonometry, :sin, :cos, :tan, :csc, :sec, :cot, :arcsin, :arccos, :arctan, :arccsc, :arcsec, :arccot, :simple_shapes_area, :simple_shapes_circumference, :simple_shapes_volume, :combination_shapes_area, :combination_shapes_circumference, :combination_shapes_volume, :ratios, :functions, :equation, :inequality, :plotting, :graph, :slope, :upper_bound, :lower_bound, :questions, :answers)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hw_records_helper.rb
module HwRecordsHelper
end

app/helpers/my_helper.rb
module MyHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/worksheets_helper.rb
module WorksheetsHelper
end

app/views/worksheets/_form.html.erb
<%= form_for(@worksheet) do |f| %>
  <% if @worksheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worksheet.errors.count, "error") %> prohibited this worksheet from being saved:</h2>

      <ul>
      <% @worksheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :worksheet_name %><br>
    <%= f.text_field :worksheet_name %>
  </div>
  <div class="field">
    <%= f.label :suggested_grade %><br>
    <%= f.number_field :suggested_grade %>
  </div>
  <div class="field">
    <%= f.label :arithmetic %><br>
    <%= f.check_box :arithmetic %>
  </div>
  <div class="field">
    <%= f.label :addition %><br>
    <%= f.check_box :addition %>
  </div>
  <div class="field">
    <%= f.label :subtraction %><br>
    <%= f.check_box :subtraction %>
  </div>
  <div class="field">
    <%= f.label :multiplication %><br>
    <%= f.check_box :multiplication %>
  </div>
  <div class="field">
    <%= f.label :division %><br>
    <%= f.check_box :division %>
  </div>
  <div class="field">
    <%= f.label :long_division %><br>
    <%= f.check_box :long_division %>
  </div>
  <div class="field">
    <%= f.label :reading %><br>
    <%= f.check_box :reading %>
  </div>
  <div class="field">
    <%= f.label :trick_question %><br>
    <%= f.check_box :trick_question %>
  </div>
  <div class="field">
    <%= f.label :multiple_choices %><br>
    <%= f.check_box :multiple_choices %>
  </div>
  <div class="field">
    <%= f.label :multiple_choice_answer %><br>
    <%= f.text_field :multiple_choice_answer %>
  </div>
  <div class="field">
    <%= f.label :word_problem %><br>
    <%= f.check_box :word_problem %>
  </div>
  <div class="field">
    <%= f.label :word_problem_solution_equation %><br>
    <%= f.text_area :word_problem_solution_equation %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.check_box :integer %>
  </div>
  <div class="field">
    <%= f.label :decimal %><br>
    <%= f.check_box :decimal %>
  </div>
  <div class="field">
    <%= f.label :number_of_decimals %><br>
    <%= f.number_field :number_of_decimals %>
  </div>
  <div class="field">
    <%= f.label :fraction %><br>
    <%= f.check_box :fraction %>
  </div>
  <div class="field">
    <%= f.label :fraction_to_decimal %><br>
    <%= f.check_box :fraction_to_decimal %>
  </div>
  <div class="field">
    <%= f.label :decimal_to_fraction %><br>
    <%= f.check_box :decimal_to_fraction %>
  </div>
  <div class="field">
    <%= f.label :significant_digits %><br>
    <%= f.number_field :significant_digits %>
  </div>
  <div class="field">
    <%= f.label :scientific_notation %><br>
    <%= f.check_box :scientific_notation %>
  </div>
  <div class="field">
    <%= f.label :parenthesis %><br>
    <%= f.check_box :parenthesis %>
  </div>
  <div class="field">
    <%= f.label :exponent %><br>
    <%= f.check_box :exponent %>
  </div>
  <div class="field">
    <%= f.label :roots %><br>
    <%= f.check_box :roots %>
  </div>
  <div class="field">
    <%= f.label :square_root %><br>
    <%= f.check_box :square_root %>
  </div>
  <div class="field">
    <%= f.label :cube_root %><br>
    <%= f.check_box :cube_root %>
  </div>
  <div class="field">
    <%= f.label :factoring %><br>
    <%= f.check_box :factoring %>
  </div>
  <div class="field">
    <%= f.label :foil %><br>
    <%= f.check_box :foil %>
  </div>
  <div class="field">
    <%= f.label :variables %><br>
    <%= f.check_box :variables %>
  </div>
  <div class="field">
    <%= f.label :number_of_variables %><br>
    <%= f.number_field :number_of_variables %>
  </div>
  <div class="field">
    <%= f.label :imaginary_number %><br>
    <%= f.check_box :imaginary_number %>
  </div>
  <div class="field">
    <%= f.label :degree %><br>
    <%= f.check_box :degree %>
  </div>
  <div class="field">
    <%= f.label :radian %><br>
    <%= f.check_box :radian %>
  </div>
  <div class="field">
    <%= f.label :trigonometry %><br>
    <%= f.check_box :trigonometry %>
  </div>
  <div class="field">
    <%= f.label :sin %><br>
    <%= f.check_box :sin %>
  </div>
  <div class="field">
    <%= f.label :cos %><br>
    <%= f.check_box :cos %>
  </div>
  <div class="field">
    <%= f.label :tan %><br>
    <%= f.check_box :tan %>
  </div>
  <div class="field">
    <%= f.label :csc %><br>
    <%= f.check_box :csc %>
  </div>
  <div class="field">
    <%= f.label :sec %><br>
    <%= f.check_box :sec %>
  </div>
  <div class="field">
    <%= f.label :cot %><br>
    <%= f.check_box :cot %>
  </div>
  <div class="field">
    <%= f.label :arcsin %><br>
    <%= f.check_box :arcsin %>
  </div>
  <div class="field">
    <%= f.label :arccos %><br>
    <%= f.check_box :arccos %>
  </div>
  <div class="field">
    <%= f.label :arctan %><br>
    <%= f.check_box :arctan %>
  </div>
  <div class="field">
    <%= f.label :arccsc %><br>
    <%= f.check_box :arccsc %>
  </div>
  <div class="field">
    <%= f.label :arcsec %><br>
    <%= f.check_box :arcsec %>
  </div>
  <div class="field">
    <%= f.label :arccot %><br>
    <%= f.check_box :arccot %>
  </div>
  <div class="field">
    <%= f.label :simple_shapes_area %><br>
    <%= f.check_box :simple_shapes_area %>
  </div>
  <div class="field">
    <%= f.label :simple_shapes_circumference %><br>
    <%= f.check_box :simple_shapes_circumference %>
  </div>
  <div class="field">
    <%= f.label :simple_shapes_volume %><br>
    <%= f.check_box :simple_shapes_volume %>
  </div>
  <div class="field">
    <%= f.label :combination_shapes_area %><br>
    <%= f.check_box :combination_shapes_area %>
  </div>
  <div class="field">
    <%= f.label :combination_shapes_circumference %><br>
    <%= f.check_box :combination_shapes_circumference %>
  </div>
  <div class="field">
    <%= f.label :combination_shapes_volume %><br>
    <%= f.check_box :combination_shapes_volume %>
  </div>
  <div class="field">
    <%= f.label :ratios %><br>
    <%= f.check_box :ratios %>
  </div>
  <div class="field">
    <%= f.label :functions %><br>
    <%= f.check_box :functions %>
  </div>
  <div class="field">
    <%= f.label :equation %><br>
    <%= f.check_box :equation %>
  </div>
  <div class="field">
    <%= f.label :inequality %><br>
    <%= f.check_box :inequality %>
  </div>
  <div class="field">
    <%= f.label :plotting %><br>
    <%= f.check_box :plotting %>
  </div>
  <div class="field">
    <%= f.label :graph %><br>
    <%= f.check_box :graph %>
  </div>
  <div class="field">
    <%= f.label :slope %><br>
    <%= f.check_box :slope %>
  </div>
  <div class="field">
    <%= f.label :upper_bound %><br>
    <%= f.text_field :upper_bound %>
  </div>
  <div class="field">
    <%= f.label :lower_bound %><br>
    <%= f.text_field :lower_bound %>
  </div>
  <div class="field">
    <%= f.label :questions %><br>
    <%= f.text_area :questions %>
  </div>
  <div class="field">
    <%= f.label :answers %><br>
    <%= f.text_area :answers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/worksheets/edit.html.erb
<h1>Editing Worksheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @worksheet %> |
<%= link_to 'Back', worksheets_path %>

app/views/worksheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Worksheets</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Description</th>
      <th>Worksheet name</th>
      <th>Suggested grade</th>
      <th>Arithmetic</th>
      <th>Addition</th>
      <th>Subtraction</th>
      <th>Multiplication</th>
      <th>Division</th>
      <th>Long division</th>
      <th>Reading</th>
      <th>Trick question</th>
      <th>Multiple choices</th>
      <th>Multiple choice answer</th>
      <th>Word problem</th>
      <th>Word problem solution equation</th>
      <th>Integer</th>
      <th>Decimal</th>
      <th>Number of decimals</th>
      <th>Fraction</th>
      <th>Fraction to decimal</th>
      <th>Decimal to fraction</th>
      <th>Significant digits</th>
      <th>Scientific notation</th>
      <th>Parenthesis</th>
      <th>Exponent</th>
      <th>Roots</th>
      <th>Square root</th>
      <th>Cube root</th>
      <th>Factoring</th>
      <th>Foil</th>
      <th>Variables</th>
      <th>Number of variables</th>
      <th>Imaginary number</th>
      <th>Degree</th>
      <th>Radian</th>
      <th>Trigonometry</th>
      <th>Sin</th>
      <th>Cos</th>
      <th>Tan</th>
      <th>Csc</th>
      <th>Sec</th>
      <th>Cot</th>
      <th>Arcsin</th>
      <th>Arccos</th>
      <th>Arctan</th>
      <th>Arccsc</th>
      <th>Arcsec</th>
      <th>Arccot</th>
      <th>Simple shapes area</th>
      <th>Simple shapes circumference</th>
      <th>Simple shapes volume</th>
      <th>Combination shapes area</th>
      <th>Combination shapes circumference</th>
      <th>Combination shapes volume</th>
      <th>Ratios</th>
      <th>Functions</th>
      <th>Equation</th>
      <th>Inequality</th>
      <th>Plotting</th>
      <th>Graph</th>
      <th>Slope</th>
      <th>Upper bound</th>
      <th>Lower bound</th>
      <th>Questions</th>
      <th>Answers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @worksheets.each do |worksheet| %>
      <tr>
        <td><%= worksheet.author %></td>
        <td><%= worksheet.description %></td>
        <td><%= worksheet.worksheet_name %></td>
        <td><%= worksheet.suggested_grade %></td>
        <td><%= worksheet.arithmetic %></td>
        <td><%= worksheet.addition %></td>
        <td><%= worksheet.subtraction %></td>
        <td><%= worksheet.multiplication %></td>
        <td><%= worksheet.division %></td>
        <td><%= worksheet.long_division %></td>
        <td><%= worksheet.reading %></td>
        <td><%= worksheet.trick_question %></td>
        <td><%= worksheet.multiple_choices %></td>
        <td><%= worksheet.multiple_choice_answer %></td>
        <td><%= worksheet.word_problem %></td>
        <td><%= worksheet.word_problem_solution_equation %></td>
        <td><%= worksheet.integer %></td>
        <td><%= worksheet.decimal %></td>
        <td><%= worksheet.number_of_decimals %></td>
        <td><%= worksheet.fraction %></td>
        <td><%= worksheet.fraction_to_decimal %></td>
        <td><%= worksheet.decimal_to_fraction %></td>
        <td><%= worksheet.significant_digits %></td>
        <td><%= worksheet.scientific_notation %></td>
        <td><%= worksheet.parenthesis %></td>
        <td><%= worksheet.exponent %></td>
        <td><%= worksheet.roots %></td>
        <td><%= worksheet.square_root %></td>
        <td><%= worksheet.cube_root %></td>
        <td><%= worksheet.factoring %></td>
        <td><%= worksheet.foil %></td>
        <td><%= worksheet.variables %></td>
        <td><%= worksheet.number_of_variables %></td>
        <td><%= worksheet.imaginary_number %></td>
        <td><%= worksheet.degree %></td>
        <td><%= worksheet.radian %></td>
        <td><%= worksheet.trigonometry %></td>
        <td><%= worksheet.sin %></td>
        <td><%= worksheet.cos %></td>
        <td><%= worksheet.tan %></td>
        <td><%= worksheet.csc %></td>
        <td><%= worksheet.sec %></td>
        <td><%= worksheet.cot %></td>
        <td><%= worksheet.arcsin %></td>
        <td><%= worksheet.arccos %></td>
        <td><%= worksheet.arctan %></td>
        <td><%= worksheet.arccsc %></td>
        <td><%= worksheet.arcsec %></td>
        <td><%= worksheet.arccot %></td>
        <td><%= worksheet.simple_shapes_area %></td>
        <td><%= worksheet.simple_shapes_circumference %></td>
        <td><%= worksheet.simple_shapes_volume %></td>
        <td><%= worksheet.combination_shapes_area %></td>
        <td><%= worksheet.combination_shapes_circumference %></td>
        <td><%= worksheet.combination_shapes_volume %></td>
        <td><%= worksheet.ratios %></td>
        <td><%= worksheet.functions %></td>
        <td><%= worksheet.equation %></td>
        <td><%= worksheet.inequality %></td>
        <td><%= worksheet.plotting %></td>
        <td><%= worksheet.graph %></td>
        <td><%= worksheet.slope %></td>
        <td><%= worksheet.upper_bound %></td>
        <td><%= worksheet.lower_bound %></td>
        <td><%= worksheet.questions %></td>
        <td><%= worksheet.answers %></td>
        <td><%= link_to 'Show', worksheet %></td>
        <td><%= link_to 'Edit', edit_worksheet_path(worksheet) %></td>
        <td><%= link_to 'Destroy', worksheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worksheet', new_worksheet_path %>

app/views/worksheets/new.html.erb
<h1>New Worksheet</h1>

<%= render 'form' %>

<%= link_to 'Back', worksheets_path %>

app/views/worksheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @worksheet.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @worksheet.description %>
</p>

<p>
  <strong>Worksheet name:</strong>
  <%= @worksheet.worksheet_name %>
</p>

<p>
  <strong>Suggested grade:</strong>
  <%= @worksheet.suggested_grade %>
</p>

<p>
  <strong>Arithmetic:</strong>
  <%= @worksheet.arithmetic %>
</p>

<p>
  <strong>Addition:</strong>
  <%= @worksheet.addition %>
</p>

<p>
  <strong>Subtraction:</strong>
  <%= @worksheet.subtraction %>
</p>

<p>
  <strong>Multiplication:</strong>
  <%= @worksheet.multiplication %>
</p>

<p>
  <strong>Division:</strong>
  <%= @worksheet.division %>
</p>

<p>
  <strong>Long division:</strong>
  <%= @worksheet.long_division %>
</p>

<p>
  <strong>Reading:</strong>
  <%= @worksheet.reading %>
</p>

<p>
  <strong>Trick question:</strong>
  <%= @worksheet.trick_question %>
</p>

<p>
  <strong>Multiple choices:</strong>
  <%= @worksheet.multiple_choices %>
</p>

<p>
  <strong>Multiple choice answer:</strong>
  <%= @worksheet.multiple_choice_answer %>
</p>

<p>
  <strong>Word problem:</strong>
  <%= @worksheet.word_problem %>
</p>

<p>
  <strong>Word problem solution equation:</strong>
  <%= @worksheet.word_problem_solution_equation %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @worksheet.integer %>
</p>

<p>
  <strong>Decimal:</strong>
  <%= @worksheet.decimal %>
</p>

<p>
  <strong>Number of decimals:</strong>
  <%= @worksheet.number_of_decimals %>
</p>

<p>
  <strong>Fraction:</strong>
  <%= @worksheet.fraction %>
</p>

<p>
  <strong>Fraction to decimal:</strong>
  <%= @worksheet.fraction_to_decimal %>
</p>

<p>
  <strong>Decimal to fraction:</strong>
  <%= @worksheet.decimal_to_fraction %>
</p>

<p>
  <strong>Significant digits:</strong>
  <%= @worksheet.significant_digits %>
</p>

<p>
  <strong>Scientific notation:</strong>
  <%= @worksheet.scientific_notation %>
</p>

<p>
  <strong>Parenthesis:</strong>
  <%= @worksheet.parenthesis %>
</p>

<p>
  <strong>Exponent:</strong>
  <%= @worksheet.exponent %>
</p>

<p>
  <strong>Roots:</strong>
  <%= @worksheet.roots %>
</p>

<p>
  <strong>Square root:</strong>
  <%= @worksheet.square_root %>
</p>

<p>
  <strong>Cube root:</strong>
  <%= @worksheet.cube_root %>
</p>

<p>
  <strong>Factoring:</strong>
  <%= @worksheet.factoring %>
</p>

<p>
  <strong>Foil:</strong>
  <%= @worksheet.foil %>
</p>

<p>
  <strong>Variables:</strong>
  <%= @worksheet.variables %>
</p>

<p>
  <strong>Number of variables:</strong>
  <%= @worksheet.number_of_variables %>
</p>

<p>
  <strong>Imaginary number:</strong>
  <%= @worksheet.imaginary_number %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @worksheet.degree %>
</p>

<p>
  <strong>Radian:</strong>
  <%= @worksheet.radian %>
</p>

<p>
  <strong>Trigonometry:</strong>
  <%= @worksheet.trigonometry %>
</p>

<p>
  <strong>Sin:</strong>
  <%= @worksheet.sin %>
</p>

<p>
  <strong>Cos:</strong>
  <%= @worksheet.cos %>
</p>

<p>
  <strong>Tan:</strong>
  <%= @worksheet.tan %>
</p>

<p>
  <strong>Csc:</strong>
  <%= @worksheet.csc %>
</p>

<p>
  <strong>Sec:</strong>
  <%= @worksheet.sec %>
</p>

<p>
  <strong>Cot:</strong>
  <%= @worksheet.cot %>
</p>

<p>
  <strong>Arcsin:</strong>
  <%= @worksheet.arcsin %>
</p>

<p>
  <strong>Arccos:</strong>
  <%= @worksheet.arccos %>
</p>

<p>
  <strong>Arctan:</strong>
  <%= @worksheet.arctan %>
</p>

<p>
  <strong>Arccsc:</strong>
  <%= @worksheet.arccsc %>
</p>

<p>
  <strong>Arcsec:</strong>
  <%= @worksheet.arcsec %>
</p>

<p>
  <strong>Arccot:</strong>
  <%= @worksheet.arccot %>
</p>

<p>
  <strong>Simple shapes area:</strong>
  <%= @worksheet.simple_shapes_area %>
</p>

<p>
  <strong>Simple shapes circumference:</strong>
  <%= @worksheet.simple_shapes_circumference %>
</p>

<p>
  <strong>Simple shapes volume:</strong>
  <%= @worksheet.simple_shapes_volume %>
</p>

<p>
  <strong>Combination shapes area:</strong>
  <%= @worksheet.combination_shapes_area %>
</p>

<p>
  <strong>Combination shapes circumference:</strong>
  <%= @worksheet.combination_shapes_circumference %>
</p>

<p>
  <strong>Combination shapes volume:</strong>
  <%= @worksheet.combination_shapes_volume %>
</p>

<p>
  <strong>Ratios:</strong>
  <%= @worksheet.ratios %>
</p>

<p>
  <strong>Functions:</strong>
  <%= @worksheet.functions %>
</p>

<p>
  <strong>Equation:</strong>
  <%= @worksheet.equation %>
</p>

<p>
  <strong>Inequality:</strong>
  <%= @worksheet.inequality %>
</p>

<p>
  <strong>Plotting:</strong>
  <%= @worksheet.plotting %>
</p>

<p>
  <strong>Graph:</strong>
  <%= @worksheet.graph %>
</p>

<p>
  <strong>Slope:</strong>
  <%= @worksheet.slope %>
</p>

<p>
  <strong>Upper bound:</strong>
  <%= @worksheet.upper_bound %>
</p>

<p>
  <strong>Lower bound:</strong>
  <%= @worksheet.lower_bound %>
</p>

<p>
  <strong>Questions:</strong>
  <%= @worksheet.questions %>
</p>

<p>
  <strong>Answers:</strong>
  <%= @worksheet.answers %>
</p>

<%= link_to 'Edit', edit_worksheet_path(@worksheet) %> |
<%= link_to 'Back', worksheets_path %>