config/routes.rb
Rails.application.routes.draw do

  get 'my/curriculums'

  get 'my/worksheets'

  get 'my/courses'

  devise_for :users

  resources :questions do
    resources :question_comments
  end
  
  resources :dashboard
  
  resources :curriculums

  resources :courses do
    resources :course_comments
  end

  resources :hw_records

  resources :worksheets do
    resources :worksheet_comments
  end

  get 'home/contact'
  
  get 'home/AboutUs'
  

  
  get 'my/questions'

  get 'question_comments/destory'
  
  get 'question_comments/create'

  get 'question_comments/destroy'
  
  devise_scope :user do
    root to: "devise/sessions#new" 
  end
   
  mathjax 'mathjax'

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :course_comments
  has_and_belongs_to_many :worksheets
  has_and_belongs_to_many :curriculums
end

app/models/course_comment.rb
class CourseComment < ActiveRecord::Base
end

app/models/courseandcurriculum.rb
class Courseandcurriculum < ActiveRecord::Base
end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
  has_many :general_comments
  has_and_belongs_to_many :curriculums
end

app/models/general_comment.rb
class GeneralComment < ActiveRecord::Base
end

app/models/hw_record.rb
class HwRecord < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :question_comments
  has_and_belongs_to_many :worksheets
end

app/models/question_comment.rb
class QuestionComment < ActiveRecord::Base
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/worksheet.rb
class Worksheet < ActiveRecord::Base
  has_many :worksheet_comments
  has_and_belongs_to_many :questions
  has_and_belongs_to_many :courses
end

app/models/worksheet_comment.rb
class WorksheetComment < ActiveRecord::Base
end

app/models/worksheetandcourse.rb
class Worksheetandcourse < ActiveRecord::Base
end

app/controllers/hw_records_controller.rb
class HwRecordsController < ApplicationController
  before_action :set_hw_record, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @hw_records = HwRecord.all
    respond_with(@hw_records)
  end

  def show
    respond_with(@hw_record)
  end

  def new
    @hw_record = HwRecord.new
    respond_with(@hw_record)
  end

  def edit
  end

  def create
    @hw_record = HwRecord.new(hw_record_params)
    @hw_record.save
    respond_with(@hw_record)
  end

  def update
    @hw_record.update(hw_record_params)
    respond_with(@hw_record)
  end

  def destroy
    @hw_record.destroy
    respond_with(@hw_record)
  end

  private
    def set_hw_record
      @hw_record = HwRecord.find(params[:id])
    end

    def hw_record_params
      params.require(:hw_record).permit(:worksheet, :questions, :student_answers, :students_name, :completeness, :grade, :grader_comments, :class_id)
    end
end

app/controllers/my_controller.rb
class MyController < ApplicationController
  def questions
   @questions = Question.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end

  def worksheets
    @worksheets = Worksheets.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end
  
  def courses
    @courses = Courses.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end
  
  def curriculums
    @curriculums = Curriculums.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hw_records_helper.rb
module HwRecordsHelper
end

app/helpers/my_helper.rb
module MyHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/worksheets_helper.rb
module WorksheetsHelper
end

app/views/hw_records/_form.html.erb
<%= form_for(@hw_record) do |f| %>
  <% if @hw_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hw_record.errors.count, "error") %> prohibited this hw_record from being saved:</h2>

      <ul>
      <% @hw_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :worksheet %><br>
    <%= f.text_field :worksheet %>
  </div>
  <div class="field">
    <%= f.label :questions %><br>
    <%= f.text_area :questions %>
  </div>
  <div class="field">
    <%= f.label :student_answers %><br>
    <%= f.text_area :student_answers %>
  </div>
  <div class="field">
    <%= f.label :students_name %><br>
    <%= f.text_field :students_name %>
  </div>
  <div class="field">
    <%= f.label :completeness %><br>
    <%= f.text_field :completeness %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.text_field :grade %>
  </div>
  <div class="field">
    <%= f.label :grader_comments %><br>
    <%= f.text_area :grader_comments %>
  </div>
  <div class="field">
    <%= f.label :class_id %><br>
    <%= f.text_field :class_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hw_records/edit.html.erb
<h1>Editing Hw Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @hw_record %> |
<%= link_to 'Back', hw_records_path %>

app/views/hw_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hw Records</h1>

<table>
  <thead>
    <tr>
      <th>Worksheet</th>
      <th>Questions</th>
      <th>Student answers</th>
      <th>Students name</th>
      <th>Completeness</th>
      <th>Grade</th>
      <th>Grader comments</th>
      <th>Class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hw_records.each do |hw_record| %>
      <tr>
        <td><%= hw_record.worksheet %></td>
        <td><%= hw_record.questions %></td>
        <td><%= hw_record.student_answers %></td>
        <td><%= hw_record.students_name %></td>
        <td><%= hw_record.completeness %></td>
        <td><%= hw_record.grade %></td>
        <td><%= hw_record.grader_comments %></td>
        <td><%= hw_record.class_id %></td>
        <td><%= link_to 'Show', hw_record %></td>
        <td><%= link_to 'Edit', edit_hw_record_path(hw_record) %></td>
        <td><%= link_to 'Destroy', hw_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hw record', new_hw_record_path %>

app/views/hw_records/new.html.erb
<h1>New Hw Record</h1>

<%= render 'form' %>

<%= link_to 'Back', hw_records_path %>

app/views/hw_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Worksheet:</strong>
  <%= @hw_record.worksheet %>
</p>

<p>
  <strong>Questions:</strong>
  <%= @hw_record.questions %>
</p>

<p>
  <strong>Student answers:</strong>
  <%= @hw_record.student_answers %>
</p>

<p>
  <strong>Students name:</strong>
  <%= @hw_record.students_name %>
</p>

<p>
  <strong>Completeness:</strong>
  <%= @hw_record.completeness %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @hw_record.grade %>
</p>

<p>
  <strong>Grader comments:</strong>
  <%= @hw_record.grader_comments %>
</p>

<p>
  <strong>Class:</strong>
  <%= @hw_record.class_id %>
</p>

<%= link_to 'Edit', edit_hw_record_path(@hw_record) %> |
<%= link_to 'Back', hw_records_path %>