config/routes.rb
Rails.application.routes.draw do

  get 'my/curriculums'

  get 'my/worksheets'

  get 'my/courses'

  devise_for :users

  resources :questions do
    resources :question_comments
  end
  
  resources :dashboard
  
  resources :curriculums

  resources :courses do
    resources :course_comments
  end

  resources :hw_records

  resources :worksheets do
    resources :worksheet_comments
  end

  get 'home/contact'
  
  get 'home/AboutUs'
  

  
  get 'my/questions'

  get 'question_comments/destory'
  
  get 'question_comments/create'

  get 'question_comments/destroy'
  
  devise_scope :user do
    root to: "devise/sessions#new" 
  end
   
  mathjax 'mathjax'

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :course_comments
  has_and_belongs_to_many :worksheets
  has_and_belongs_to_many :curriculums
end

app/models/course_comment.rb
class CourseComment < ActiveRecord::Base
end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
  has_many :general_comments
  has_and_belongs_to_many :curriculums
end

app/models/general_comment.rb
class GeneralComment < ActiveRecord::Base
end

app/models/hw_record.rb
class HwRecord < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :question_comments
  has_and_belongs_to_many :worksheets
end

app/models/question_comment.rb
class QuestionComment < ActiveRecord::Base
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/worksheet.rb
class Worksheet < ActiveRecord::Base
  has_many :worksheet_comments
  has_and_belongs_to_many :questions
  has_and_belongs_to_many :courses
end

app/models/worksheet_comment.rb
class WorksheetComment < ActiveRecord::Base
end

app/models/worksheetandcourse.rb
class Worksheetandcourse < ActiveRecord::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @courses = Course.all
    respond_with(@courses)
  end

  def show
    respond_with(@course)
  end

  def new
    @course = Course.new
    respond_with(@course)
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.save
    respond_with(@course)
  end

  def update
    @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:class_id, :teacher, :students, :course_name, :class_description, :corresponding_course)
    end
end

app/controllers/my_controller.rb
class MyController < ApplicationController
  def questions
   @questions = Question.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end

  def worksheets
    @worksheets = Worksheets.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end
  
  def courses
    @courses = Courses.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end
  
  def curriculums
    @curriculums = Curriculums.where(author: current_user.username).paginate(:per_page => 5, :page => params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hw_records_helper.rb
module HwRecordsHelper
end

app/helpers/my_helper.rb
module MyHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/worksheets_helper.rb
module WorksheetsHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :class_id %><br>
    <%= f.text_field :class_id %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :students %><br>
    <%= f.text_area :students %>
  </div>
  <div class="field">
    <%= f.label :course_name %><br>
    <%= f.text_field :course_name %>
  </div>
  <div class="field">
    <%= f.label :class_description %><br>
    <%= f.text_area :class_description %>
  </div>
  <div class="field">
    <%= f.label :corresponding_course %><br>
    <%= f.text_field :corresponding_course %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table>
  <thead>
    <tr>
      <th>Class</th>
      <th>Teacher</th>
      <th>Students</th>
      <th>Course name</th>
      <th>Class description</th>
      <th>Corresponding course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.class_id %></td>
        <td><%= course.teacher %></td>
        <td><%= course.students %></td>
        <td><%= course.course_name %></td>
        <td><%= course.class_description %></td>
        <td><%= course.corresponding_course %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class:</strong>
  <%= @course.class_id %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @course.teacher %>
</p>

<p>
  <strong>Students:</strong>
  <%= @course.students %>
</p>

<p>
  <strong>Course name:</strong>
  <%= @course.course_name %>
</p>

<p>
  <strong>Class description:</strong>
  <%= @course.class_description %>
</p>

<p>
  <strong>Corresponding course:</strong>
  <%= @course.corresponding_course %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>